// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBehl70TV-LVHlqYRxX8kFJhyWFd1Ngzws',
    appId: '1:55376137124:web:17e829d0b17331bd24cf31',
    messagingSenderId: '55376137124',
    projectId: 'farectory-388ce',
    authDomain: 'farectory-388ce.firebaseapp.com',
    storageBucket: 'farectory-388ce.appspot.com',
    measurementId: 'G-DY39WF4RPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0jflAgkZy20T9feI_xcJ-SS4IHlwYsaM',
    appId: '1:55376137124:android:268861e88fca6e7a24cf31',
    messagingSenderId: '55376137124',
    projectId: 'farectory-388ce',
    storageBucket: 'farectory-388ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM1ieoLyZ8sFphP6deUA3FUpTB7kW8Kfw',
    appId: '1:55376137124:ios:94b67101fcc9214124cf31',
    messagingSenderId: '55376137124',
    projectId: 'farectory-388ce',
    storageBucket: 'farectory-388ce.appspot.com',
    iosBundleId: 'com.example.farectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM1ieoLyZ8sFphP6deUA3FUpTB7kW8Kfw',
    appId: '1:55376137124:ios:94b67101fcc9214124cf31',
    messagingSenderId: '55376137124',
    projectId: 'farectory-388ce',
    storageBucket: 'farectory-388ce.appspot.com',
    iosBundleId: 'com.example.farectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBehl70TV-LVHlqYRxX8kFJhyWFd1Ngzws',
    appId: '1:55376137124:web:f262f07037e8bd6624cf31',
    messagingSenderId: '55376137124',
    projectId: 'farectory-388ce',
    authDomain: 'farectory-388ce.firebaseapp.com',
    storageBucket: 'farectory-388ce.appspot.com',
    measurementId: 'G-YK8NK127JK',
  );
}
